### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cordoval** [simPod/KafkaBundle#2]
this package uses the bindings for the extension rdkafka and package with stubs "kwn/php-rdkafka-stubs": "^1.0", and this is only for consumers, and i cannot do a producer?

what is wrong with https://github.com/weiboad/kafka-php
why is this not a requirement for this bundle?

I am curious also why https://github.com/weiboad/kafka-php in its composer.json does not have some dependency to the php extension.

Can you please illuminate me a little bit? Thanks pal

**Comment by simPod** [comment]
Hey! This package leverages https://github.com/arnaud-lb/php-rdkafka and not https://github.com/weiboad/kafka-php, that's why it isn't in composer.json. Because it is not a required dependency.

1. I found php-rdkafka performance and stability to be on a much higher level than kafka-php's one
2. kafka-php is still in a development and honestly I think not suitable for production
3. php-rdkafka provides access to more settings than kafka-php

You can do producer but you don't need a bundle for that. Simply create and register a service that produces messages as mentioned in https://github.com/arnaud-lb/php-rdkafka#producing and you're good to go.

**Comment by cordoval** [comment]
does php-rdkafka supports versions of kafka 1.0.0? or will in the near future?
the thing is confluent brings in a set of things easy to deploy, but it brings 1.0.0 as in the latest package.
So it would be great if this library you mentioned supports it. I see in the README.md that it only reaches right before.

**Comment by cordoval** [comment]
The other question i have if this bindings are just that bindings, and for instance confluent kafka java examples do support by default Avro on the serialization. kafka-php does not support Avro.
Does using php-rdkafka helps any different supporting Avro?

Thanks

**Comment by simPod** [comment]
I'm using it with kafka 1.0.0 :)

AFAIK it doesn't do anything with Avro (I'd rather ask in php-rdkafka repo as I'm not the author of it btw). I think you can implement Avro serialization so it serializes before producing the message.
